version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: guest-service-app
    volumes:
      - ../app:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
    depends_on:
      - mysql
    networks:
      - guest-network

  mysql:
    image: mysql:8.0
    container_name: guest-service-mysql
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guest_service
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - guest-network

  nginx:
    image: nginx:latest
    container_name: guest-service-nginx
    ports:
      - "8080:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - guest-network

networks:
  guest-network:
    driver: bridge

volumes:
  mysql_data:
